version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  tweet:
    <<: *defaults
    steps:
      - install
      - run: node index.js

  lyrics:
    <<: *defaults
    steps:
      - install
      - run: node lyrics.js

workflows:
  version: 2

  test:
    jobs:
      - tweet
      - lyrics

  poll:
    triggers:
      - schedule:
          # Every hour
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tweet
      - lyrics
